export const AuditAction = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  COSTING_COMPLETED: 'COSTING_COMPLETED',
  PRODUCT_APPROVED: 'PRODUCT_APPROVED',
  PRODUCT_REJECTED: 'PRODUCT_REJECTED',
  SELLING_PRICE_CHANGED: 'SELLING_PRICE_CHANGED',
  PRICING_SETTINGS_UPDATED: 'PRICING_SETTINGS_UPDATED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
